site:
  title: Serverless
  url: https://example.org/docs 
  start_page: ::index.adoc 
content:
  sources:
  - url:https://github.com/openshift-cloud-functions/Documentation.git
    branches: master
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [v2.0, v1.0]
    start_path: docs
ui:https://github.com/openshift-cloud-functions/Documentation.git
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
