// This module is included in the following assemblies:
//
// assembly_knative-minishift.adoc


[id='installing-knative-minishift_{context}']
= Installing Knative on a Minishift cluster using a script

Use the script `install-on-minishift.sh`, to install Knative on a Minishift cluster.

NOTE: `install-on-minishift.sh` is destructive. It destroys the existing `knative` profile and recreates it with a working configuration.

.Prerequisites
* You need cluster administrator privileges to install and use Knative on a Minishift cluster.


.Procedure
. Clone the `knative-operators` repository.

   `git clone https://github.com/openshift-cloud-functions/knative-operators`   
   `cd knative-operators/`   
   `git fetch --tags`   
   `git checkout openshift-v0.2.0`

. Confirm that your Minishift instance has stopped.

	`minishift stop`

. Navigate to the newly cloned repository and run the `install-on-minishift.sh` script.

	`./etc/scripts/install-on-minishift.sh`
